image:
  repository: ''
  name: test-chain
  tag: latest
imagePullSecrets:
- name: registry-pull-secret

ingress:
  enabled: true
  # className: openshift-default
  className: ""
  annotations: {}
    # route.openshift.io/termination: "edge"
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: Prefix
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local
